core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path
from django.views.static import serve



urlpatterns = [
    path("", include("modulesApp.DashboardPortal.urls")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^upload/(?P<path>.*)$', serve,{'document_root': settings.UPLOAD_ROOT}),
    path("", include("modulesApp.App.urls")),
    path("", include("modulesApp.Comunication.urls")),
    path("Planning/", include("modulesApp.Planning.urls", namespace="planning")),
    path("Helping/", include("modulesApp.Helping.urls", namespace="helping")),
    path("security/", include("modulesApp.Security.urls",namespace="security")),
    path("capacitacion/", include("modulesApp.Capacitacion.urls")),
    path("Organizational_network/", include("modulesApp.Organizational_network.urls")),
    path("payments/", include("modulesApp.Payments.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path('admin/', admin.site.urls),
    
]

modulesApp/Security/urls.py
from django.urls import path, include  # add this
from modulesApp.Security.views import login,login_view,register_view,logout_view,changePassword,\
securitySettings,changeSecretQuestion,recovery_method, recovery_method_question,forgot_password, \
account_recovery, testvue, testdata , editProfile, images, borrarImages, rootImages, renderListasCombos,verificationaccount, review_new_register,Modaltransfersec
app_name = "security"
urlpatterns = [
    path("login/", login_view, name="login"),
    path("register/", register_view, name="register"),
    path("logout/", logout_view, name="logout"),
    path("changePassword/", changePassword, name="changePassword"),
    path("changeSecretQuestion/", changeSecretQuestion, name="changeSecretQuestion"),
    path("securitySettings/", securitySettings, name="securitySettings"),
    path("recoverymethod/", recovery_method, name="recovery_method"),
    path("recovery_method_question/", recovery_method_question, name="recovery_method_question"),
    path("forgotpassword/", forgot_password, name="forgot_password"),
    path("account_recovery/<str:activation_key>/",account_recovery , name="account_recovery"),
    path("testvue/", testvue, name="testvue"),
    path("testdata/", testdata, name="testdata"),
    path("editProfile/", editProfile, name='editProfile'),
    path("images/", images, name='images'),
    path("rootImages/", rootImages, name='rootImages'),
    path("borrarImages/", borrarImages, name='borrarImages'),
    path('renderListasCombos', renderListasCombos, name='renderListasCombos'),
    path("verificationaccount/<str:activation_key>/", verificationaccount, name="verification_account"),
    path('new_register', review_new_register, name='new_register'),
    path('Modaltransfersec', Modaltransfersec, name='Modaltransfersec'),
    
    

]

modulesApp/Security/forms.py
from django.conf import settings
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm
from django.contrib.auth import get_user_model
from modulesApp.App.models import ConfTablasConfiguracion, AppPublico

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = settings.AUTH_USER_MODEL

class SignUpForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput())
    email = forms.EmailField(widget=forms.EmailInput())
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')
        
class ResetPasswordForm(PasswordResetForm):
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Email o Usuario",
                "class": "form-control"
            }
        ))


class RecoveryMethodForm(ResetPasswordForm):
    typeMethod = forms.CharField(widget=forms.NumberInput)
    
    
class RecoveryMethodEmail(forms.Form):
    password1 = forms.CharField()
    password2 = forms.CharField()


class RecoveryMethodQuestion(forms.Form):
    secrettext = forms.CharField()

class editProfiles(forms.ModelForm):
    nombre = forms.CharField(label='Nombre',
                             widget=forms.TextInput(
                                 attrs={
                                     "placeholder": "Agrega tu nombre",
                                     "class": "form-control form-control-line",
                                     'maxlength': 15,

                                 }
                             ))

    apellido = forms.CharField(label='Apellido',
                               widget=forms.TextInput(
                                   attrs={
                                       "placeholder": "Agrega tu apellido",
                                       "class": "form-control form-control-line",
                                       'maxlength': 100,
                                       "name": "Last Name"
                                   }
                               ))
    pais = forms.ModelChoiceField(queryset=ConfTablasConfiguracion.obtenerHijos("countries_iso"), empty_label="Selecciona tu pais?",label='Pais:',
    widget=forms.Select(
        attrs={        
            "placeholder" : "Selecciona un pais",        
            "class": "form-control",
        }
    )) 

    direccion = forms.CharField(label='Direccion',
                                widget=forms.TextInput(
                                    attrs={
                                        "placeholder": "Agrega una direccion",
                                        "class": "form-control form-control-line",
                                        'maxlength': 200
                                    }
                                ))

    telefono_principal = forms.CharField(label='Telefono Principal', required=False,
                                widget=forms.NumberInput(
                                    attrs={
                                        "placeholder": "Agrega un telefono",
                                        "class": "form-control form-control-line",
                                        'maxlength': 100
                                    }
                                ))

    correo_principal = forms.CharField(label='Correo Alternativo', required=False,
                              widget=forms.EmailInput(
                                  attrs={
                                      "placeholder": "Agregue un correo alternativo",
                                      "class": "form-control form-control-line",
                                      'maxlength': 100
                                  }
                              ))
    class Meta:
        model = AppPublico
        exclude=('telegram_id','user_id')

modulesApp/Security/views.py
from django.shortcuts import render,redirect,reverse, HttpResponseRedirect
import datetime
# Create your views here.
from django.views import View
from .forms import LoginForm, SignUpForm, ResetPasswordForm, RecoveryMethodForm , RecoveryMethodQuestion, \
    RecoveryMethodEmail,editProfiles
from django.contrib.auth import login, logout, update_session_auth_hash
from .models import User, CodigoVerificacion
from .methods import es_correo_valido,change_password,get_status_user, auth_user, is_user_exists, \
    send_vefication_code_email, get_verification_code , verificarenlace, create_publico, restablecer_cuenta
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password, check_password
from django.http import HttpResponse, JsonResponse, HttpResponseForbidden
from django.template import loader
from django.template.loader import render_to_string
from modulesApp.App.models import ConfTablasConfiguracion, AppPublico,ConfSettings_Atributo
from ..Organizational_network.models import nodos_grupos,nodos_gruposIntegrantes
from core import settings
from django.http import Http404
from pathlib import Path
from django.core.files.storage import FileSystemStorage
import imghdr
from django.core.paginator import Paginator
import os
import json
from django.template.loader import render_to_string
from ..Comunication.methods import create_mail, send_mail
from django.template.defaulttags import register
@register.filter
def jsonmail(datos):
  if datos==None or datos=="" or datos=={}:
    return ""
  tlf=None
  data = json.loads(datos)

  
  if data==None or data=="" or data=={}:
      return ""
  if   'emailPrincipal' in data :
     return data['emailPrincipal']
  else:
      return ""
@register.filter
def verifica_existe_nodo(datos):
    aprob=False
    nodos=nodos_grupos.objects.get(valor_elemento="Nodo_inicial")
    integra=nodos_gruposIntegrantes.objects.filter(fk_nodogrupo=nodos,fk_public_id=datos) 
    if integra.exists():
        aprob= True
    else:
        aprob=False  
    return aprob      
def login_view(request):
    if request.user.is_authenticated:
        print()
        print(request.user)
        return redirect("Dashboard")
    else:
         
         if request.method == "POST":
             print('ko')
             print(request.user.is_authenticated)
             form = LoginForm(request.POST or None)
             if form.is_valid():          
                status_user = auth_user(form.cleaned_data.get("username"), form.cleaned_data.get("password"))
                if status_user['estado'] == "Active" or status_user['estado'] == "Active unverified":
                    
                    login(request, status_user['user']) 
                    return redirect("Dashboard")
                if status_user['estado'] == "Password expired":
                    tipo_operacion = ConfTablasConfiguracion.objects.filter(valor_elemento="tv_cambio_clave")[0]
                    code = str(get_verification_code(status_user['user'],3,tipo_operacion))
                    if code:
                        request.session['cambio_clave'] = True
                        return redirect('security:account_recovery',activation_key=str(code))
                    else:
                        messages.error(request, "Error to generate code activaction")
                else:
                    messages.error(request, status_user['estado'] +":"+ status_user['mensaje'])                           
             else:
                messages.error(request, form.errors.as_text())              
         return render(request, "index.html",{"login_show":True})
         
def register_view(request):
    login_show = False
    if request.user.is_authenticated:
        return redirect("Dashboard")
    else:    
        if request.method == "POST":
            form = SignUpForm(request.POST)
            if form.is_valid():
                if User.objects.filter(email__exact=form.cleaned_data.get('email')).count() == 0:
                   users = form.save()
                   publico=create_publico(form.cleaned_data.get('email'),users)
                   roles=User.objects.get(pk=publico.user_id_id)
                   roles.fk_rol_usuario=ConfTablasConfiguracion.objects.filter(valor_elemento="Interesado")[0]
                   roles.save()
                   tipo=ConfTablasConfiguracion.objects.filter(valor_elemento="tv_validar_cuenta")[0]
                   print(tipo)
                   nodos= nodos_grupos.objects.filter(valor_elemento="Nodo_inicial")
                   if nodos.exists():
                      nodo_inicial=nodos_gruposIntegrantes.objects.create()
                      nodo_inicial.fk_nodogrupo=nodos[0]
                      nodo_inicial.fk_public=publico
                      nodo_inicial.fecha_incorporacion=datetime.datetime.now()
                      nodo_inicial.status_integrante=ConfTablasConfiguracion.objects.get(valor_elemento='Status_activo')
                      nodo_inicial.save()
                   rango=ConfSettings_Atributo.objects.filter(valor_setting='security_verify')
                   rango_dias=ConfSettings_Atributo.objects.filter(valor_setting='security_expiracion')
                   if rango_dias.exists():
                      datos=json.loads(rango_dias.rangovalor_setting)
                   if rango.exists():
                    if rango[0].status_setting == 1:
                      code = str(get_verification_code(users,int(datos['max']),tipo))
                      enlace = request.get_raw_uri().split("//")[0] + "//" + \
                               request.get_host() + "/verificationaccount/" + code + "/"
                      context = {"titulo": "Account Verification", "user": users,
                                 "content": "Thank you for joining the " + str(
                                   settings.EMPRESA_NOMBRE) + " team, to verify your account click on the following link: ",
                                 "enlace": enlace, "enlaceTexto": "click here!", "informacion": 'informacion.descripcion',
                                 "empresa": settings.EMPRESA_NOMBRE,
                                 "urlimage": settings.EMPRESA_SRC_LOGO, "empresa_contact": 'settings.EMPRESA_CONTACT_PAGE',
                                 "empresa_email": 'settings.'}
                      print(context)
                      send_mail(
                       create_mail(users, "Account Verification Request", "security/base_email_template_pro.html",
                                context))
                      information = {
                       "mensaje": "Le hemos enviado un enlace de verificación de cuenta al correo electrónico proporcionado. Recuerda revisar la carpeta de spam",
                       "titulo": "El enlace de registro ha sido enviado", "urlimage": settings.EMPRESA_SRC_LOGO,
                       "imagelocal": settings.EMPRESA_SRC_LOGO}
                      return render(request, "information_view.html", information)
                    else:
                       messages.success(request, "Te has registrado con exito inicia session para ingresar.")
                       login_show = True
            else:
                messages.error(request, form.errors.as_text())
    return render(request, "index.html",{"login_show":login_show})
def verificationaccount(request, activation_key):
    try:
        enlace = CodigoVerificacion.objects.get(activation_key=activation_key)
        if enlace.usuario.CtaUsuario.fk_status_cuenta != "suspend":
            if verificarenlace(enlace.key_expires):
                print("enlace valido", activation_key)
                context = {"user": enlace.usuario.user.username}
                if request.method == "GET":
                    restablecer_cuenta(enlace)
                    login(request, enlace.usuario.user)
                    return redirect("/registration/enrollment/")
            else:
                information = {"mensaje": "El enlace que estas intentando usar ha expirado por favor solicita otro.",
                               "titulo": "Enlace Expirado", "urlimage": settings.EMPRESA_URL_LOGO,
                               "imagelocal": settings.EMPRESA_SRC_LOGO}
                return render(request, "security/information_view.html", information)
        else:
            information = {"mensaje": "Esta cuenta de usuario se encuentra bloqueada por favor comunicate con el soporte.",
                           "titulo": "Cuenta Bloqueada", "urlimage": settings.EMPRESA_URL_LOGO,
                           "imagelocal": settings.EMPRESA_SRC_LOGO}
            return render(request, "information_view.html", information)
    except CodigoVerificacion.DoesNotExist:
        information = {"mensaje": "El enlace que estas intentando usar es invalido o ha expirado."+
            "\n Los enlaces de verificacion enviados a tu correo son de un solo uso por tanto no se pueden reutilizar,\n"+
            "si estas intentando verificar tu cuenta es posible que ya este verificada verificalo iniciando sesion, \n"+
            "si buscas recuperar tu cuenta intenta realizar el proceso nuevamente asegurandote de abrir en enlace una vez de forma correcta,\n"+
            "aun asi si el problema persiste o piensas que esto es un error comunicate a nuestros canales de soporte.",
                       "titulo": "Enlace Invalido", "urlimage": settings.EMPRESA_URL_LOGO,
                       "imagelocal": settings.EMPRESA_SRC_LOGO}
        return render(request, "information_view.html", information)

 
@login_required(login_url="security/login/")
def changePassword(request):
    if request.method == 'POST':
        actual_password = request.POST.get('password')

modulesApp/Security/templates/profilePage.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="content">
    <div class="page-inner animated fadeInRight">
        <div class="page-header">
            <h4 class="page-title">Mi perfil</h4>
            <ul class="breadcrumbs">
                <li class="nav-home">
                    <a href="{% url 'home' %}">
                        <i class="flaticon-home"></i>
                    </a>
                </li>
                <li class="separator">
                    <i class="flaticon-right-arrow"></i>
                </li>
                <li class="nav-item">
                    <span>Mi perfil</span>
                </li>             
            </ul>
        </div>
        <div class="page-category">
            <div class="row">
                <div class="col-lg-4 col-xlg-3 col-md-5">
                    <div class="card">
                        <div class="card-body">
                            <center class="mt-4"> 
                                
                                    <div class="image-upload">
                                        <div class="row">
                                            <div class="col">
                                                <label for="file-input">
                                                    {%if img%}
                                                    <img src="/upload/user/{{img}}" class="rounded-circle border" style="cursor: pointer;" width="150" id="imagenPerfil">
                                                    {%else%}
                                                    <img src="/static/assets/img/default-user-icon.png" class="rounded-circle border" style="cursor: pointer;" width="150" id="imagenPerfil">
                    
                                                    {%endif%}
                                                   
                                                    
                                                </label>  
                                                <input id="file-input" name="file-input" type="file" style="display: none;" accept="image/*" />
                                            </div>
                                        </div>
                                        <div class="row mt-2">
                                            <div class="col" id="buttons">
                                                <button class="btn btn-primary btn-round" onclick=clickImage()>Agregue una foto</button>
                                            </div>
                                        </div>
                                    </div> 

            
                                <h4 class="card-title my-2">
                                    {{request.user.username}}
                                </h4>
                                <h6 class="card-subtitle">
                                    {{ request.user.email }}
                                </h6>
                            </center>
                        </div>
                        <div>
                            <hr> </div>
                        <div class="card-body text-center"> 
                            <small class="text-muted">Direccion de correo </small>
                            <h6>{{ request.user.email }}</h6> 
                            <small class="text-muted pt-4 db">Telefono</small>
                            <h6>{{telefono}}</h6> 
                            <small class="text-muted pt-4 db">Direcion</small>
                            <h6>{{form.direccion.value}}</h6>
                        </div>
                    </div>
                </div>
            
            
                <div class="col-lg-8 col-xlg-9 col-md-7">
                    <div class="card">
                        <div class="card-header bg-dark2">
                            <span class="h1 text-white d-flex justify-content-center">Mi Informacion</span>
                        </div>
                        <div class="card-body m-0 p-0">
                            <form method="post" action="" id="formulario">
                                {% csrf_token %}
            
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-12">
                
                                            {% for p in form %}  
            
                                                <div class="form-group">
                                                    <label for="{{ p.auto_id }}" >{{p.label}}</label>
                                                    <div class="input-group">
                                                        {{ p }}   
                                                        {% if p.field.widget.input_type == 'select' %}
                                                            
                                                            <div class="input-group-prepend" id="{{ p.auto_id }}" >
                                                                <span class="input-group-text">
                                                                    <i class="fas fa-search"></i>
                                                                </span>
                                                            </div>
            
                                                        {% endif %}
                                                    </div>
                                                    
                                                </div>
            
                                            {% endfor %} 
                
                                        </div>
                                    </div>
                                </div>
                                <div class="card-action d-flex justify-content-end">
                                    <button type="submit" class="btn btn-primary btn-lg text-white">Guardar <i class="fas fa-save ml-1"></i></button>
                                    {% if activo %}
                                    <span id="next" class="btn btn-primary">Siguiente
                                        <i class="fas fa-arrow-right"></i>
                                    </span>
                                    {% endif %}
                                </div>
                               
                            </form>  
                        </div>
                    </div>
                </div>
            </div>                           
        </div>
    </div>
</div>


{% include 'Planning/mensajes.html' %}  

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script>

    // metodos para cargar botones de imagenes
    $(document).ready(function(){

        if('{{img}}'.toLowerCase()!=='none'){

            document.getElementById('buttons').innerHTML = '<button class="btn btn-primary btn-round mr-2" onclick=clickImage()>Change</button><button class="btn btn-danger btn-round" onclick=borrarImage()>Quitar</button>'

        }else{

            document.getElementById('buttons').innerHTML = '<button class="btn btn-primary btn-round" onclick=clickImage()>Agregue una foto</button>'

        }

    });

    // metodo borrar imagen
    function borrarImage() {

        alerta(3).then((willDelete) => {

            if(willDelete){

                $.ajax({
                    type: "POST",
                    url: "{% url 'security:borrarImages' %}", 
                    data : {csrfmiddlewaretoken: '{{ csrf_token }}'},
                    success: function (response) {

                        if(response.mensaje){
                            
                            $(".avatar-img").attr('src', "/static/assets/img/default-user-icon.png")
                            $('#imagenPerfil').attr('src', "/static/assets/img/default-user-icon.png" );
                            swal(response.mensaje)
                            document.getElementById('buttons').innerHTML = '<button class="btn btn-primary btn-round" onclick=clickImage()>Agregue una foto</button>'
                            
                        }

                    },
                    error: function () {}
                });
                
            }

        });

    }

    // metodos para disparar el gestor de imagen
    function clickImage() {

        $( "#file-input").trigger('click')
        
    }

    //metodos para guardar imagen
    $(document).on('change', "#file-input", function(e){
    //     // console.log(document.getElementById("file-input").files[0].fullName)
    //     // $('#imagenPerfil').attr('src', document.getElementById("file-input").files[0].path);
        
    //   const file = document.querySelector('#file-input').files[0];

    //   if(file){
        
    //   const reader = new FileReader();
    //             reader.onload = imageIsLoaded;
    //             reader.readAsDataURL(file);
    //   }else
      console.log("nada")

        // $('#fileForm').submit()
    var x = document.getElementById("file-input")
    var txt = "";
        if (x.files.length > 0) {

            var file = x.files[0];
            if((file.size / 1024 / 1024).toFixed(2) > 6){

                swal("Max Upload size is 6MB only")

            }else if(!(x.files[0].type.toLowerCase().endsWith('/png')||x.files[0].type.toLowerCase().endsWith('/jpg')||x.files[0].type.toLowerCase().endsWith('/jpeg'))){

                swal("Only JPG, JPEG and PNG file types are allowed")

            }else{

               // $('#fileForm').submit()
                var formdata = new FormData();
                formdata.append('file-input', file);
                formdata.append('csrfmiddlewaretoken', '{{ csrf_token }}');
                
                $.ajax({
                        type: "POST",
                        url: "{% url 'security:images' %}", 
                        data : formdata,
                        processData: false,
                        contentType: false,
                         success: function (response) {

                            if(response.mensaje){
                                
                                const reader = new FileReader();
                                reader.onload = imageIsLoaded;
                                reader.readAsDataURL(file);
                                swal(response.mensaje)
                                document.getElementById('buttons').innerHTML = '<button class="btn btn-primary btn-round mr-2" onclick=clickImage()>Cambiar</button><button class="btn btn-danger btn-round" onclick=borrarImage()>Remove</button>'
                                
                            }

                                

                        },
                        error: function () {}
                });

            }

        }
        
    });

    function imageIsLoaded(e) {

        $(".avatar-img").attr('src', e.target.result)
        $('#imagenPerfil').attr('src', e.target.result );

    }


	

	// metodos filtro combo
	$("#formulario").on('click', ".input-group-prepend", function(e){

        if(document.getElementById('myBrowser')==null){
            // console.log( $(this).attr('name'))

            // console.log($(this).prev().attr('name'))
            
            console.log($(this).prev().is('.countryList'))
            const d = $(this)
            
            $.ajax({
                    type: "POST",
                    url: "{% url 'security:renderListasCombos' %}", 
                    data : {    
                    clave: $(this).prev().attr('name'),
                    tipo: 'TablasConfiguracion',
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                },
                success: function (response) {

                    // document.getElementById('paginas').innerHTML = response.paginas;
                    // document.getElementById('tablaContenido').innerHTML = response.contenido;
                    // // console.log(response.contenido)
                    d.before(response.lista)
                    $("#myBrowser").focus()

                },
                error: function () {}
            });

        }
    })	 

    $("#formulario").on('focusout', "#myBrowser", function(e){

        $('#browsers').remove()

        $('#myBrowser').remove()

    })

    $("#formulario").on('input keydown', "#myBrowser", function(e){

        let val = this.value;
        let id

        if($('#browsers option').filter(function(){return this.value.toUpperCase() === val.toUpperCase()}).length && e.keyCode == 13) {
            
            id = $('#browsers option').filter(function(){return this.value.toUpperCase() === val.toUpperCase()})[0].id

            $('#myBrowser').prev().val(id)

            $('#myBrowser').blur()

        }

    });

    
    $(document).on('keydown', "form input", function(e){

        if (e.keyCode == 13) {
            e.preventDefault();
            return false;
        }

    })
    
     {% comment %} const nextBtn = document.querySelector('#next')
    
  
  
     nextBtn.addEventListener('click', ()=>{
        window.location.href ="{% url 'home'%}";
           

    }) {% endcomment %}

</script>
{% endblock javascripts %}

modulesApp/Security/templates/testVue.html
{% extends "baseexternal.html" %}

{% block title %} List Data {% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    <div class="d-flex justify-content-center text-center">
        <div class="row col-md-6 d-flex justify-content-center">
          <div  id="app">
          </div>
        </div>
    </div>    

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}
<script type="importmap">
    {
      "imports": {
        "vue": "https://unpkg.com/vue@3/dist/vue.esm-browser.js"
      }
    }
  </script>

<script type="module">
    import { createApp } from 'vue'
    import MyComponent from '/static/assets/js/vue/my-component.js'
    let ruta = "{% url 'security:testdata' %}"
    let app = createApp(MyComponent).mount('#app')
    app.ruta = ruta
  </script>
{% endblock javascripts %}




                            

     