core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path
from django.views.static import serve



urlpatterns = [
    path("", include("modulesApp.DashboardPortal.urls")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^upload/(?P<path>.*)$', serve,{'document_root': settings.UPLOAD_ROOT}),
    path("", include("modulesApp.App.urls")),
    path("", include("modulesApp.Comunication.urls")),
    path("Planning/", include("modulesApp.Planning.urls", namespace="planning")),
    path("Helping/", include("modulesApp.Helping.urls", namespace="helping")),
    path("security/", include("modulesApp.Security.urls",namespace="security")),
    path("capacitacion/", include("modulesApp.Capacitacion.urls")),
    path("Organizational_network/", include("modulesApp.Organizational_network.urls")),
    path("payments/", include("modulesApp.Payments.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path('admin/', admin.site.urls),
    
]

modulesApp/Helping/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from modulesApp.Helping import views
app_name = "helping"
urlpatterns = [

    path('nuevo/', views.nuevo, name="nuevo"),  
    path('modalAddAyuda', views.modalAddAyuda, name='modalAddAyuda'),
    path('modalGuardarAyuda', views.modalGuardarAyuda, name='modalGuardarAyuda'),
    path('modalBuscarAyuda', views.modalBuscarAyuda, name='modalBuscarAyuda'),
    path('modalEliminarAyuda', views.modalEliminarAyuda, name='modalEliminarAyuda'),
    path('modalAddPagina', views.modalAddPagina, name='modalAddPagina'),
    path('modalPdf', views.modalPdf, name='modalPdf'),
    path('modalGuardarPagina', views.modalGuardarPagina, name='modalGuardarPagina'),
    path('modalHijosPagina', views.modalHijosPagina, name='modalHijosPagina'),
    path('modalEliminarHijoPagina', views.modalEliminarHijoPagina, name='modalEliminarHijoPagina'),
    path('modalAddCarruserl', views.modalAddCarruserl, name='modalAddCarruserl'),
    path('modalGuardarImagen', views.modalGuardarImagen, name='modalGuardarImagen'),
    path('modalGuardarPdf', views.modalGuardarPdf, name='modalGuardarPdf'),
    path('modalEliminarImagen', views.modalEliminarImagen, name='modalEliminarImagen'),
    path('modalPaginaMover', views.modalPaginaMover, name='modalPaginaMover'),
    path('Url/<int:id>', views.Url, name='Url'),
    path('contenidoAyudaMiniatura', views.contenidoAyudaMiniatura, name='contenidoAyudaMiniatura'),
    path('filtrar', views.filtrar, name='filtrar'),
    

    path('validarTituloAyuda', views.validarTituloAyuda, name='validarTituloAyuda'),
    path('copiarLInk', views.copiarLInk, name='copiarLInk'),
    path('filtroLista', views.filtroLista, name='filtroLista'),
    path('filtroElemento', views.filtroElemento, name='filtroElemento'),
]

core/templates/App/portalSettings.html
{% extends "layouts/base.html" %}

{% block title %}{% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

	<div class="content">
		<div class="page-inner animated fadeInRight">
			<div class="page-header">
				<h4 class="page-title">Configuraciones</h4>
				<ul class="breadcrumbs">
					<li class="nav-home">
						<a href="{% url 'home' %}">
							<i class="flaticon-home"></i>
						</a>
					</li>
					<li class="separator">
						<i class="flaticon-right-arrow"></i>
					</li>
					<li class="nav-item">
						<span>Configuracion</span>
					</li>
				</ul>
			</div>
			<div class="page-category">
				<div class="card">
					<div class="card-body">
						<div class="form-row d-flex justify-content-center">

                            <div class="form-group col-md-3 d-flex justify-content-center">
								<div class="card" style="width: 20rem;">
									<div class="card-header text-center" style="background-color: #1a2035 !important;color: white;">
										<h3>Configurar ayudas</h3>
									</div>
									<div class="card-body">
											<img class="card-img" src="https://static.campusproductivity.com/assets/img/preguntas-mas-frecuentes.png" alt="Card image cap">
									</div>
									<div class="card-footer d-flex justify-content-center">
										<button class="btn btn-primary btn-block"> <a href="{% url 'helping:nuevo' %}" class="button btn btn-primary">Acceder</a></button>
									</div>
								</div>
							</div>


                            <div class="form-group col-md-3 d-flex justify-content-center">
								<div class="card" style="width: 20rem;">
									<div class="card-header text-center" style="background-color: #1a2035 !important;color: white;">
										<h3>Configurar Preferencias</h3>
									</div>
									<div class="card-body">
											<img class="card-img" src="https://static.campusproductivity.com/assets/img/simple.jpg" alt="Card image cap">
									</div>
									<div class="card-footer d-flex justify-content-center">
										<button class="btn btn-primary btn-block"> <a href="{% url 'preferencias' %}" class="button btn btn-primary">Acceder</a></button>
									</div>
								</div>
							</div>

						</div>
					</div>
				</div>       			            
            </div>
		</div>
	</div>

{% endblock content %}
	
<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
{% endblock javascripts %}