core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path
from django.views.static import serve



urlpatterns = [
    path("", include("modulesApp.DashboardPortal.urls")),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^upload/(?P<path>.*)$', serve,{'document_root': settings.UPLOAD_ROOT}),
    path("", include("modulesApp.App.urls")),
    path("", include("modulesApp.Comunication.urls")),
    path("Planning/", include("modulesApp.Planning.urls", namespace="planning")),
    path("Helping/", include("modulesApp.Helping.urls", namespace="helping")),
    path("security/", include("modulesApp.Security.urls",namespace="security")),
    path("capacitacion/", include("modulesApp.Capacitacion.urls")),
    path("Organizational_network/", include("modulesApp.Organizational_network.urls")),
    path("payments/", include("modulesApp.Payments.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path('admin/', admin.site.urls),
    
]

modulesApp/App/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from modulesApp.App import views

urlpatterns = [

    # The home page
    # path('', views.index, name='home'),
    path('App/Favorito/mostrarfavoritos/', views.mostrarfavoritos, name='mostrarfavoritos'), 
    path('App/Favorito/añadirFavoritos/', views.añadirFavoritos, name='añadirFavoritos'),
    path('App/configuracion/', views.configuracion, name='configuracion'),
    path('App/settings/scales/', views.scales, name='scales'),
    path('App/settings/scalesGeAddModal/', views.scalesGeAddModal, name='modalScaleGeAdd'),
    path('App/settings/tabla', views.componentTabla, name='component_tabla'),   
    #Calendar & index settings
    path('App/settings/preferencias/', views.preferencias, name='preferencias'),
    path('App/settings/modalprefer/', views.getmodalprefer, name='modalprefer'),
    path('App/settings/saveprefer/', views.saveprefer, name='saveprefer'),
    path('App/settings/upprefer/', views.setprefer, name='updatepre'),
    path('App/settings/combobox/', views.combobox, name='combobox'),
    path('App/settings/tables/', views.tablesettings, name='tables'),
    path('App/settings/contentables/', views.getcontentablas, name='contentables'),
    path('App/settings/verhijos/', views.gethijos, name='verhijos'),
    path('App/settings/modalAddSetting/', views.getModalSetting, name="modalAddSetting"),
    path('App/settings/deletesetting/', views.deletehijos, name="deletesetting"),
    path('App/settings/editsetting/', views.edithijos, name="editsetting"),
    path('App/settings/managepersons/', views.managepersons, name="managepersons"),
    path('App/settings/unlockPublic/', views.unlockPublic, name='unlockPublic'),
    path('App/settings/lockPublic/', views.lockPublic, name='lockPublic'),
    path('App/settings/listaRol/', views.listaRol, name='listaRol'),
    path('App/settings/setRole/', views.setRole, name='setRole'),
    path('App/settings/paginar/', views.paginar, name='paginar'),
    #Security Settings
    

    # Scales
    

    # notificacioines
    
    
    # Matches any html file
    

]

modulesApp/Helping/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from modulesApp.Helping import views
app_name = "helping"
urlpatterns = [

    path('nuevo/', views.nuevo, name="nuevo"),  
    path('modalAddAyuda', views.modalAddAyuda, name='modalAddAyuda'),
    path('modalGuardarAyuda', views.modalGuardarAyuda, name='modalGuardarAyuda'),
    path('modalBuscarAyuda', views.modalBuscarAyuda, name='modalBuscarAyuda'),
    path('modalEliminarAyuda', views.modalEliminarAyuda, name='modalEliminarAyuda'),
    path('modalAddPagina', views.modalAddPagina, name='modalAddPagina'),
    path('modalPdf', views.modalPdf, name='modalPdf'),
    path('modalGuardarPagina', views.modalGuardarPagina, name='modalGuardarPagina'),
    path('modalHijosPagina', views.modalHijosPagina, name='modalHijosPagina'),
    path('modalEliminarHijoPagina', views.modalEliminarHijoPagina, name='modalEliminarHijoPagina'),
    path('modalAddCarruserl', views.modalAddCarruserl, name='modalAddCarruserl'),
    path('modalGuardarImagen', views.modalGuardarImagen, name='modalGuardarImagen'),
    path('modalGuardarPdf', views.modalGuardarPdf, name='modalGuardarPdf'),
    path('modalEliminarImagen', views.modalEliminarImagen, name='modalEliminarImagen'),
    path('modalPaginaMover', views.modalPaginaMover, name='modalPaginaMover'),
    path('Url/<int:id>', views.Url, name='Url'),
    path('contenidoAyudaMiniatura', views.contenidoAyudaMiniatura, name='contenidoAyudaMiniatura'),
    path('filtrar', views.filtrar, name='filtrar'),
    

    path('validarTituloAyuda', views.validarTituloAyuda, name='validarTituloAyuda'),
    path('copiarLInk', views.copiarLInk, name='copiarLInk'),
    path('filtroLista', views.filtroLista, name='filtroLista'),
    path('filtroElemento', views.filtroElemento, name='filtroElemento'),
]

modulesApp/Planning/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from modulesApp.Planning import views

app_name = "planning"
urlpatterns = [

    path('func_Planning/', views.func_Planning, name='func_Planning'),
    path('configuracion/', views.configuracion, name='configuracion'),
    path('render_fihas/', views.render_fihas, name='renderfihas'),
    path('renderTablas/', views.renderTablas, name='renderTablas'),
    path('testfi/', views.testfi, name='testfi'),
    path('guardarFicha/', views.guardarFicha, name='guardarFicha'),
    path('eliminarFicha/', views.eliminarFicha, name='eliminarFicha'),
    path('moverFicha/', views.moverFicha, name='moverFicha'),
    path('mostrarFicha/', views.mostrarFicha, name='mostrarFicha'),
    path('fichaPersonal/<int:idFicha>/', views.fichaPersonal),
    path('fichaPersonal/<int:idFicha>/<int:idUser>/', views.fichaPersonalUsuario),
    path('guardarFichaPersonal/', views.guardarFichaPersonal, name='guardarFichaPersonal'),
    path('guardarBloque/', views.guardarBloque, name='guardarBloque'),
    path('eliminarBloque/', views.eliminarBloque, name='eliminarBloque'),
    path('previsualizarBloque/<int:idFicha>/', views.previsualizarFicha),
    path('previsualizarBloque/<int:idFicha>/<int:id>/', views.previsualizarBloque),
    path('moverBloque/', views.moverBloque, name='moverBloque'),
    path('guardarAtributo/', views.guardarAtributo, name='guardarAtributo'),
    path('eliminarAtributo/', views.eliminarAtributo, name='eliminarAtributo'),
    path('moverAtributo/', views.moverAtributo, name='moverAtributo'),
    path('atributoLista/', views.atributoLista, name='atributoLista'),
    path('listaPerfiles/', views.listaPerfiles, name='listaPerfiles'),
    path('listasExternas/', views.listasExternas, name='listasExternas'),
    path('guardarListaExterna/', views.guardarListaExterna, name='guardarListaExterna'),
    path('contenidoListaExterna/', views.contenidoListaExterna, name='contenidoListaExterna'),
    path('eliminarListaExterna/', views.eliminarListaExterna, name='eliminarListaExterna'),
    path('addproceso/', views.addproceso, name='addproceso'),
    path('guardarListaExternaHijo/', views.guardarListaExternaHijo, name='guardarListaExternaHijo'),
    path('eliminarListaExternaHijo/', views.eliminarListaExternaHijo, name='eliminarListaExternaHijo'),
    
    

    # modales    
    path('modalFicha/', views.modalFicha, name='modalFicha'),
    path('modalListaBloque/', views.modalListaBloque, name='modalListaBloque'),
    path('modalBloque/', views.modalBloque, name='modalBloque'),
    path('modalAtributo/', views.modalAtributo, name='modalAtributo'),
    path('modalListaExterna/', views.modalListaExterna, name='modalListaExterna'),
    path('modalListaExternaHijo/', views.modalListaExternaHijo, name='modalListaExternaHijo'),

    # metodos
    path('validarNombreFicha/', views.validarNombreFicha, name='validarNombreFicha'),

    # filtro
    path('filtroLista/', views.filtroLista, name='filtroLista'),
    path('filtroAtributo/', views.filtroAtributo, name='filtroAtributo'),
    path('filtroElemento/', views.filtroElemento, name='filtroElemento'),
    path('filtrar/', views.filtrar, name='filtrar'),


]

modulesApp/TabPersonal/models.py
from django.db import models

# Create your models here.

modulesApp/TabPersonal/views.py
from django.shortcuts import render

# Create your views here.

core/templates/TabPersonal/carpPlanning/contenidoAtributo.html
{% load i18n %}
{% for page in data%}
{% include 'TabPersonal/carpPlanning/contenidoAtributoIndividual.html' with page=page lista=lista %}  
{% endfor %}

core/templates/TabPersonal/carpPlanning/listaPerfiles.html
{% extends "layouts/base.html" %}
{% load i18n %}
{% block title %}{% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
<style>

   @media(max-width: 800px){
      .card-list-item-title {
         font-size: 5vw;
      }
   }

   .btn-radius{
   border: 3px solid rgba(100, 100, 100, 0.1);
   border-radius: 3rem;
   color: #fff;
   cursor: pointer;
   padding: 10px;
   width: 130px;
   transition: 0.6s;
   }
   .btn-azul{
   background: none;
   background-size: 300%;
   background-image: linear-gradient(to left, #00B7DA, #161569, #00B7DA);
   }
   .btn-mora{
   background: none;
   background-size: 300%;
   background-image: linear-gradient(to left, #A950A1, #2D3A54, #A950A1);
   }
   .btn-rosa{
   background: none;
   background-size: 300%;
   background-image: linear-gradient(to left, #ffcae3, #ff499d, #ffcae3);
   }
   .btn-naranja{
   background: none;
   background-size: 300%;
   background-image: linear-gradient(to left, #ff5733, #b81b57, #ff5733);
   }
   .btn-radius:hover{
   background-position: right;
   }
	input::-webkit-outer-spin-button,
	input::-webkit-inner-spin-button {

		-webkit-appearance: none;
		margin: 0;

	}

	input[type=number] {

		-moz-appearance: textfield;

	}

   @media(max-width: 400px){

      #collapseCardSearch {

         padding-left: 0!important;
         padding-right: 0!important;

      }

      div.d-flex.justify-content-around > button > strong{

         display: none;

      }

      div.d-flex.justify-content-around > button > i{

         margin-right: 0!important;

      }

      #paginas > select{

         margin-right: 0!important;

      }

      #paginas > ul{

         flex-wrap: wrap;

      }

      #paginas {

         flex-wrap: wrap;
         justify-content: center;

      }

   }

</style>
{% endblock stylesheets %}

{% block content %}

   <div class="content">
      <div class="page-inner">
         <div class="page-header mb-3">
            <h4 class="page-title">Planificacion</h4>
            <ul class="breadcrumbs">
               <li class="nav-home">
                  <a href="{% url 'Dashboard' %}">
                     <i class="flaticon-home"></i>
                  </a>
               </li>
               <li class="separator">
                  <i class="flaticon-right-arrow"></i>
               </li>
               <li class="nav-item">
                  <span>Planificacion</span>
               </li>
               <li class="separator">
                  <i class="flaticon-right-arrow"></i>
               </li>
               <li class="nav-item">
                  <a href="#">Tabla de registros</a>
               </li>
            </ul>
         </div>

         <div class="page-category">

            <main class="card shadow mb-4">
               <section class="card-header">
                  <a href="#collapseCardSearch" class="d-block d-flex align-items-center justify-content-between collapsed px-5" data-toggle="collapse" style="text-decoration:none" role="button" aria-expanded="false" aria-controls="collapseCardExample">
                     <h3 class="m-0 font-weight-bold text-dark"> <i class="fa fa-search mr-1" style="color:rgb(0, 119, 255);"></i>Buscar...</h3>
                     <i class="fa fa-angle-down fa-2x" style="color:rgb(0, 119, 255);"></i>
                  </a>
                  <div class="collapse px-5" id="collapseCardSearch">
                     <form class="form-group" id="formFiltro"></form>
                     <div class="d-flex justify-content-around">
                        <button class="btn btn-success" type="button" onclick="anadirFiltro()"><i class="fas fa-plus mr-1"></i><strong>{% translate 'Agregar' %}</strong></button>
                        <button class="btn btn-primary" id="btnFiltro" type="button" onclick="buscarFiltro()"><i class="fa fa-search mr-1"></i><strong>{% translate 'Buscar' %}</strong></button>
                        <button class="btn btn-danger" type="button" onclick="eliminarFiltroAll()"><i class="fa fa-eraser mr-1"></i><strong>{% translate 'Limpiar' %}</strong></button>
                     </div>
                  </div>
               </section>
               <section class="card-body">
                  <div id="renderContainer" class="col-md-12 mx-1 table-responsive"></div>
               </section>
               <section class="card-footer d-flex align-items-center" id="paginas">
                  {% include 'Helping/paginas.html' with plan=plan %}   
               </section>
            </main>
         </div>
      </div>
   </div>
{% endblock content %}
	
<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script>

   $(document).ready(function () {

      renderContent()

   });

   const renderContent = () => {

      document.querySelector("#renderContainer").innerHTML = spinnerBar()
      fetch("{% url 'planning:renderTablas' %}", {
         ...fetchObject,
         body: JSON.stringify({
            numero: localStorage.getItem("rango"),
         })
      })
      .then(res => res.json())
      .then(text => {

         document.querySelector("#renderContainer").innerHTML = text['contenido']
         document.querySelector("#paginas").innerHTML = text['pagina']

      })
      .catch((err)=>{

         makeMessage(4, "{% translate 'Error' %}", "{% translate 'Ha ocurrido un error y no se pudo procesar su solicitud' %}", 'fa fa-exclamation-triangle')
         document.querySelector("#renderContainer").innerHTML = ''

      })

   }


   
   // metodos para los filtros
   const eliminarFiltro = (e, multiple = false) => {

      let nodo = e.parentNode.parentNode
      
      if (multiple)

         nodo = nodo.parentNode

      nodo.previousElementSibling.remove()
      nodo.parentNode.removeChild(nodo);

   }

   const eliminarFiltroAll = () => {

      if(!document.querySelector('.progress-bar')){

         const formFiltro = document.querySelector('#formFiltro')
         formFiltro.innerHTML = ""
         const btnFiltro = document.querySelector('#btnFiltro')
         btnFiltro.click()

      }else

         makeMessage(3,"{% translate 'Alerta' %}","{% translate 'Debes esperar a que el contenido termine de cargarse' %}")

   }

   const anadirFiltro = () => {

      setLoading()   
      fetch("{% url 'planning:filtroLista' %}", {
         ...fetchObject,
      })
      .then(res => res.text())
      .then(text => {

         document.querySelector('#formFiltro').insertAdjacentHTML("beforeend", text)

      })
      .catch((err)=>{

         makeMessage(4, "{% translate 'Error' %}", "{% translate 'Ha ocurrido un error y no se pudo procesar su solicitud' %}", 'fa fa-exclamation-triangle')

      })
      .finally(() => {

         stopLoading()

      })

   }

   const anadirFiltroAtributo = (e) => {

      setLoading() 
      id = e.options[e.selectedIndex].value
      fetch("{% url 'planning:filtroAtributo' %}", {
         ...fetchObject,
         body: JSON.stringify({

            id,

         })
      })
      .then(res => res.json())
      .then(text => {
         
         if(text){
            
            e.innerHTML = text['contenido']
            e.setAttribute("onchange", "anadirFiltroHijo(this)");
            e.setAttribute("name", id);
            e.parentNode.previousElementSibling.innerHTML = `<strong>${text['pagina']}</strong>`
         }

      })
      .catch((err)=>{

         makeMessage(4, "{% translate 'Error' %}", "{% translate 'Ha ocurrido un error y no se pudo procesar su solicitud' %}", 'fa fa-exclamation-triangle')

      })
      .finally(() => {

         stopLoading()

      })

   }
   
   const anadirFiltroHijo = (e) => {

      setLoading() 
      fetch("{% url 'planning:filtroElemento' %}", {
         ...fetchObject,
         body: JSON.stringify({

            id: e.options[e.selectedIndex].value,

         })
      })
      .then(res => res.json())
      .then(text => {
         
         if(text){

            const parent = e.parentNode
            parent.innerHTML = text['contenido']
            parent.previousElementSibling.innerHTML = `<strong>${text['pagina']}</strong>`
            parent.querySelector(':first-child').focus()

         }

      })
      .catch((err)=>{

         makeMessage(4, "{% translate 'Error' %}", "{% translate 'Ha ocurrido un error y no se pudo procesar su solicitud' %}", 'fa fa-exclamation-triangle')

      })
      .finally(() => {

         stopLoading()

      })

   }
   
   const buscarFiltro = (pag = -1) => {

      if(!document.querySelector('.progress-bar')){
         console.log(getFormFiltro())
         localStorage.setItem("rango", document.querySelector('#selectNumeracion').value);

         document.querySelector("#renderContainer").innerHTML = spinnerBar()
         fetch("{% url 'planning:filtrar' %}", {
            ...fetchObject,
            body: JSON.stringify({
               filtro: getFormFiltro(),
               numero: localStorage.getItem("rango"),
               pag: pag > 0 ? pag : document.querySelector('.page-item.active > a').dataset.number
            })
         })
         .then(res => res.json())
         .then(text => {
            
               document.querySelector("#renderContainer").innerHTML = text['contenido']
               document.querySelector("#paginas").innerHTML = text['pagina']

         })
         .catch((err)=>{

            makeMessage(4, "{% translate 'Error' %}", "{% translate 'Ha ocurrido un error y no se pudo procesar su solicitud' %}", 'fa fa-exclamation-triangle')

         })

      }else

         makeMessage(3,"{% translate 'Alerta' %}","{% translate 'Debes esperar a que el contenido termine de cargarse' %}")
         
   }

   const getFormFiltro = () => {
      
      const formFiltro = document.querySelector('#formFiltro')
      const formData = new FormData(formFiltro);
      const data = Object.fromEntries(formData.entries())

      Object.keys(data).forEach((key) => {

         if(!data[key].trim())

            delete data[key]

      });

      return data

   }

   ///////////////////////// 
   
   $(document).on('click','.page-link',(e) => {

      e.preventDefault()
      buscarFiltro(e.currentTarget.dataset.number)

   })
   
   $(document).on('mouseover mousedown','[data-toggle="tooltip"]',(e) => {

      $('[data-toggle="tooltip"]').tooltip();

   })

</script>
{% endblock javascripts %}

core/templates/TabPersonal/carpPlanning/listasExternas.html
   {% extends "layouts/base.html" %}
   {% load i18n %}
   {% block title %}{% endblock %}
   <!-- Specific Page CSS goes HERE  -->
   {% block stylesheets %}
   <style>
  
   </style>
   {% endblock stylesheets %}
   
   {% block content %}
   <div class="content">
      <div class="page-inner animated fadeInRight">
         <div class="page-header">
            <h4 class="page-title">Planificacion</h4>
            <ul class="breadcrumbs">
               <li class="nav-home">
                  <a href="{% url 'home' %}">
                     <i class="flaticon-home"></i>
                  </a>
               </li>
               <li class="separator">
                   <i class="flaticon-right-arrow"></i>
               </li>
               <li class="nav-item">
                   <span>Planificacion</span>
               </li>
               <li class="separator">
                   <i class="flaticon-right-arrow"></i>
               </li>
               <li class="nav-item">
                   <a href="{% url 'planning:configuracion' %}">Configuracion</a >
               </li>
               <li class="separator">
                   <i class="flaticon-right-arrow"></i>
               </li>
               <li class="nav-item">
                   <a href="#">Listas Externas</a >
               </li>
            </ul>
         </div>
         <div class="page-category">
            <div class="card">
               <div class="section-header">
                     <h3 class="section-title">Nueva categoria</h3>
                     <div onclick="modalListaExterna()" class="btn btn-icon btn-success btn-round add-btn btn-card-lg">
                        <i class="fas fa-plus"></i>
                     </div>
               </div> 
               <main class="card-body py-0">
                  
               </main>
            </div>
         </div>
      </div>
   </div>
   {% endblock content %}
   
   {% block javascripts %}
   <script>
      
      $(document).ready(function () {

         renderContent()

      });

      const renderContent = ()=>{

         setLoading()
         fetch("{% url 'planning:contenidoListaExterna'%}", {
            ...fetchObject,
         })
        .then(res => res.text())
        .then(text => {

            document.querySelector("main.card-body").innerHTML = text

         })
         .catch((err) => {
            
            makeMessage(4, "{% translate 'Error' %}", "{% translate 'Ha ocurrido un error y no se pudo procesar su solicitud' %}", 'fa fa-exclamation-triangle')

         })
         .finally(() => {

            stopLoading()

         })

      }

    const modalListaExterna = (id = null) => {

        setLoading()
        fetch("{% url 'planning:modalListaExterna' %}", {
            ...fetchObject,
            body: JSON.stringify({
               id
            })
        })
        .then(res => res.text())
        .then(text => {

            document.querySelector('#carruselAyuda').insertAdjacentHTML("beforebegin", text)
            const formListaExterna = document.querySelector("#formListaExterna")

            formListaExterna.addEventListener("submit", (e) => {

                e.preventDefault()
                
                const formData = new FormData(formListaExterna);
                const data = Object.fromEntries(formData.entries())

                if(data.nombre.trim()){

                  setLoading()
                  fetch("{% url 'planning:guardarListaExterna' %}", {
                     ...fetchObject,
                     body: JSON.stringify({
                     data,
                     id
                     })
                  })
                  .then(res => res.text())
                  .then(text => {

                     $("#modalListaExterna").modal("hide")
                     makeMessage(1, "{% translate 'Muy Bien!' %}", "{% translate 'Registro guardado' %}", "fa fa-check")
                     renderContent()

                  })
                  .catch((err) => {
                     
                     makeMessage(4, "{% translate 'Error' %}", "{% translate 'Ha ocurrido un error y no se pudo procesar su solicitud' %}", 'fa fa-exclamation-triangle')

                  })
                  .finally(() => {

                     stopLoading()

                  })

                }else {

                    formListaExterna.classList.add('needs-validation', 'was-validated')
                    formListaExterna.removeAttribute('novalidate');

                }
                
            })

            $('#modalListaExterna').modal('show')
            $('#modalListaExterna').on('hidden.bs.modal', function (event) {

                $('#modalListaExterna').remove()

            })

        })
        .catch((err) => {

            makeMessage(4, "{% translate 'Error' %}", "{% translate 'Ha ocurrido un error y no se pudo procesar su solicitud' %}", 'fa fa-exclamation-triangle')

        })
        .finally(() => {

            stopLoading()

        })

    }

   const openDeleteProgram = async (id) =>{

      const elimino = await alerta(3)

      if(elimino){

         setLoading()
         fetch("{% url 'planning:eliminarListaExterna'%}", {
            ...fetchObject,
            body: JSON.stringify({
               id
            })
         })
        .then(res => res.text())
        .then(text => {

            renderContent()
            makeMessage(1, "{% translate 'Muy Bien!' %}", "{% translate 'Registro eliminado' %}", "fa fa-check")

        })
        .catch((err) => {

            makeMessage(4, "{% translate 'Error' %}", "{% translate 'Ha ocurrido un error y no se pudo procesar su solicitud' %}", 'fa fa-exclamation-triangle')

        })
        .finally(() => {

            stopLoading()

        })

      }

   }

   const renderproseso = (id)=>{

      setLoading()
      fetch("{% url 'planning:addproceso'%}", {
         ...fetchObject,
         body: JSON.stringify({
            id,
         })
      })
      .then(res => res.text())
      .then(text => {

         document.querySelector("#renderpro").innerHTML = text

      })
      .catch((err) => {

         makeMessage(4, "{% translate 'Error' %}", "{% translate 'Ha ocurrido un error y no se pudo procesar su solicitud' %}", 'fa fa-exclamation-triangle')

      })
      .finally(() => {

         stopLoading()

      })

   }

   const modalListaExternaHijo = (padre, id = null) => {

      setLoading()
      fetch("{% url 'planning:modalListaExternaHijo' %}", {
         ...fetchObject,
         body: JSON.stringify({
            id,
            padre
         })
      })
      .then(res => res.text())
      .then(text => {

         document.querySelector('#carruselAyuda').insertAdjacentHTML("beforebegin", text)
         const formListaExternaHijo = document.querySelector("#formListaExternaHijo")

         formListaExternaHijo.addEventListener("submit", (e) => {

               e.preventDefault()
               const formData = new FormData(formListaExternaHijo);
               const data = Object.fromEntries(formData.entries())

               if(data.nombre.trim()){

                  setLoading()
                  fetch("{% url 'planning:guardarListaExternaHijo' %}", {
                     ...fetchObject,
                     body: JSON.stringify({
                     data,
                     id,
                     padre
                     })
                  })
                  .then(res => res.text())
                  .then(text => {

                     $("#modalListaExternaHijo").modal("hide")
                     makeMessage(1, "{% translate 'Muy Bien!' %}", "{% translate 'Registro guardado' %}", "fa fa-check")
                     renderproseso(padre)

                  })
                  .catch((err) => {
                     
                     makeMessage(4, "{% translate 'Error' %}", "{% translate 'Ha ocurrido un error y no se pudo procesar su solicitud' %}", 'fa fa-exclamation-triangle')

                  })
                  .finally(() => {

                     stopLoading()

                  })

               }else {

                  formListaExternaHijo.classList.add('needs-validation', 'was-validated')
                  formListaExternaHijo.removeAttribute('novalidate');

               }
               
         })

         $('#modalListaExternaHijo').modal('show')
         $('#modalListaExternaHijo').on('hidden.bs.modal', function (event) {

            $('#modalListaExternaHijo').remove()

         })

      })
      .catch((err) => {

         makeMessage(4, "{% translate 'Error' %}", "{% translate 'Ha ocurrido un error y no se pudo procesar su solicitud' %}", 'fa fa-exclamation-triangle')

      })
      .finally(() => {

         stopLoading()

      })

   }

   const openDeleteProseso = async (padre, id) =>{

      const elimino = await alerta(3)

      if(elimino){

         setLoading()
         fetch("{% url 'planning:eliminarListaExternaHijo'%}", {
            ...fetchObject,
            body: JSON.stringify({
               id,
               padre
            })
         })
        .then(res => res.text())
        .then(text => {

            renderproseso(padre)
            makeMessage(1, "{% translate 'Muy Bien!' %}", "{% translate 'Registro eliminado' %}", "fa fa-check")

        })
        .catch((err) => {

            makeMessage(4, "{% translate 'Error' %}", "{% translate 'Ha ocurrido un error y no se pudo procesar su solicitud' %}", 'fa fa-exclamation-triangle')

        })
        .finally(() => {

            stopLoading()

        })

      }

   }

</script>
	
{% endblock javascripts %}